#ifndef INSTRUCTION_H_
#define INSTRUCTION_H_
/* instructions */
enum {
  SOP,TXT,DAT,BSS,MAB,MAC,MBC,MCB,MCA,MBA,MAP,ADD,SUB,ADC,SBC,MUL,DIV,
  MOD,MLC,DVC,MDC,AND,ORR,EOR,SHL,SHR,CPL,CEQ,CNE,CGT,CLT,CGE,CLE,NOT,
  LDI,LDC,LDU,SDR,JMP,JPF,JPT,PSH,POP,CAL,ENT,ADJ,LEV,LEA,LIC,LON
};
#endif
